### PR TITLE
1912 1913 1915 performance optimizations 2

### LINKED ISSUE #1912: Don't error check reference count deref on envelope in production
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### LINKED ISSUE #1913: Add option to optimize memory pool when a header is not needed
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### LINKED ISSUE #1915: Cache TD pointer in scheduler triggers
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by stmcgovern**
Closes #1912.
Closes #1913.
Closes #1915.

Second PR of multiple for fine-grained performance enhancements.

### CODE REVIEW

**Comment by nlslatt** [comment]
@stmcgovern The PR tests are not making progress because you marked this ready for review after your last push. If you resign the last commit and force push, the tests will run.

**Comment by stmcgovern** [comment]
@nlslatt thank you

**Comment by PhilMiller** [comment]
Stand-alone PRs would be preferable, again for better traceability

**Comment by stmcgovern** [comment]
Split into PR #1927, #1928 and #1929.

**Pull request closed without merging**
