### PR TITLE
1247: Generate clang 9/10 workflows for Azure

### LINKED ISSUE #1247: Add clang-9, clang-10 to CI
**What Needs to be Done?**

These builds work---we should add them as CI targets on ubuntu.

### PR DESCRIPTION
**Pull request by JacobDomagala**
Fixes #1247

### CODE REVIEW

**Comment by JacobDomagala** [comment]
Both Clang 9 and 10 are using default configuration. Do we want to add anything special for them?

**Review by cz4rs — APPROVED** [review]
looks good to me!

**Review by jstrzebonski — APPROVED** [review]
Looks good

**Comment by cz4rs** [comment]
> Both Clang 9 and 10 are using default configuration. Do we want to add anything special for them?

I assume that one of these can be used for #1352, but they look just fine at the moment :+1:

**Review by lifflander — APPROVED** [review]
Looks good

**Pull request merged**
