### PR TITLE
1173 omp_lock_t is undefined on Intel serial build

### LINKED ISSUE #1173: omp_lock_t is undefined on Intel serial build
**Describe the bug**
From an EMPIRE dev:

> If I build intel-serial (no openmp), I get the compiler error,
> /pscratch/nroberd/EMPIRE/TPL/vt/src/vt/utils/mutex/omp_mutex.h(57): error: identifier "omp_lock_t" is undefined
>    omp_lock_t omp_lock;
>

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #1173

### CODE REVIEW

**Review by PhilMiller — CHANGES_REQUESTED** [review]
I don't think this is suitable. This isn't a problem of an incomplete type, it's a type that's not declared at all. We need to use `#if _OPENMP` appropriately.

**Comment by cz4rs** [comment]
@lifflander I assume that this is introduced by footprinting PR - in that case this one-liner should help


note: the description says:
> If I build intel-serial **(no openmp)**, I get the compiler error,

there is:
```cpp
#if vt_check_enabled(openmp)
```
covering all of `omp_mutex.h` content, so a build without openmp should skip this completely (?)

**Comment by cz4rs** [comment]
> I don't think this is suitable. This isn't a problem of an incomplete type, it's a type that's not declared at all. We need to use `#if _OPENMP` appropriately.

@PhilMiller I was still writing when you posted this - true, I'm trying to see what's wrong with `#if vt_check_enabled(openmp)`

**Comment by cz4rs** [comment]
ok, just to keep the discussion here: we have `clang-8, macosx` build which correctly detects the absence of OpenMP:
```
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
OpenMP not found: using std::thread for workers
```

it looks like this should be fixed on the CMake side rather then in C++ code

@lifflander can you ask the reporter for the CMake output / complete build log?

**Comment by lifflander** [comment]
> ok, just to keep the discussion here: we have `clang-8, macosx` build which correctly detects the absence of OpenMP:
> 
> ```
> -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
> -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
> -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
> OpenMP not found: using std::thread for workers
> ```
> 
> it looks like this should be fixed on the CMake side rather then in C++ code
> 
> @lifflander can you ask the reporter for the CMake output / complete build log?

I'm trying to get a full report. The dev is offline right now.. so I'm not sure when it will come

**Pull request closed without merging**
