### PR TITLE
1086 lb refactor

### LINKED ISSUE #1086: LB refectoring on the path to persistent LB instances
**What Needs to be Done?**

Work on #965 is in progress, but incomplete. There's a bunch of refactoring to be done to get there that should get merged sooner rather than later, to avoid bit rot and integration consternation. This issue is to give something for the corresponding PR to be associated with.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #1086

### CODE REVIEW

**Review by lifflander — APPROVED** [review]
Looks good to me

**Comment by PhilMiller** [comment]
Failure of clang-8/macosx/mpich was seemingly due to #958

**Comment by lifflander** [comment]
Does this preempt #1059 ?

**Review by JacobDomagala — APPROVED** [review]
I was curious about the usage of `lb_instances_` here but i can see that in PR #1059 it makes more sense if you allow `LBType::NoLB` to be a valid value

**Comment by PhilMiller** [comment]
This likely leads to #1059 being closed, though I'm not ready to jump on that yet. I just wanted to get these easy and uncontroversial bits merged now, so that they can be built upon for #875, #965, and #1055

**Pull request merged**
