### PR TITLE
1970: release `1.2.0`

### LINKED ISSUE #1970: Create release `1.2.0`
**What Needs to be Done?**
- [x] Create PR to sync `main` with `develop`
- [x] Prepare release notes
- [x] ~Update wiki~ (it points to the latest stable release already)

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #1970

### CODE REVIEW

**Comment by cz4rs** [comment]
Codacy error can be ignored.

**Comment by cz4rs** [comment]
[Draft release notes](https://github.com/DARMA-tasking/vt/releases/tag/untagged-f6e39091f1fd9beb5689) posted.

**Review by nlslatt — APPROVED** [review]
Looks good!

**Comment by nlslatt** [comment]
Hmm, there's a problem with commit signing. I'll fix it.

**Pull request merged**
