### PR TITLE
457 autohandler gcc workaround 2

### PR DESCRIPTION
**Pull request by pnstickne**
Tagged commits, same change as https://github.com/DARMA-tasking/vt/pull/468 otherwise

### CODE REVIEW

**Comment by nmm0** [comment]
> All these changes seem reasonable to fix the errors with gcc. But, this seems to break the build in somehow with `test_reduce_op`

I think this might be the no_epoch being pushed bug, I'll push a fix to this branch if so

**Comment by nmm0** [comment]
@lifflander Some of these changes duplicate https://github.com/DARMA-tasking/vt/pull/497 i.e. we both fixed the same bug. Should I go ahead and remove them from this PR? Your fix avoids the no_epoch bug and also is in a contained PR for that issue

**Comment by lifflander** [comment]
@nmm0 Can you rebase the termination fixes out of this PR? I made some other fixes to the test in the other PR so I'd rather keep that separate.

**Comment by lifflander** [comment]
@nmm0 Also, please rebase onto develop so the status checks run.

**Comment by nmm0** [comment]
The most recent version of this pull request is https://github.com/DARMA-tasking/vt/pull/502

**Pull request closed without merging**
