### PR TITLE
1336: macosx-clang build fails when using latest macos image

### LINKED ISSUE #1336: macosx-clang build fails when using latest macos image
**Describe the bug**
`macosx` build fails with a following error:
```
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at /usr/local/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)

      Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.  

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.19.6/share/cmake/Modules/FindMPI.cmake:1722 (find_package_handle_standard_args)
  cmake/load_mpi_package.cmake:6 (find_package)
  cmake/load_packages.cmake:7 (include)
  CMakeLists.txt:61 (include)
```

**To Reproduce**
Occurs at every CI build: https://github.com/DARMA-tasking/vt/actions/workflows/macosx-clang-mpich.yml.
@nmm0 has also spotted this on `kahuna` using `gcc-10`.

**Expected behavior**
Make sure that `macosx` (and any other environment where this was reported) build is passing.

**Additional context**
> @JacobDomagala  seems that the failing builds are using newer version 20210314.1:
https://github.com/actions/virtual-environments/blob/macOS-10.15/20210314.1/images/macos/macos-10.15-Readme.md
https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210314.1
Where the last build that is green was using 20210307.1:
https://github.com/actions/virtual-environments/blob/macOS-10.15/20210307.1/images/macos/macos-10.15-Readme.md
https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210307.1

> @PhilMiller The error is actually not necessarily indicative of what actually went wrong in configuration
When it’s missing support for a language, it adds a note about that to the error output that will result, even if the actual cause of failure was unrelated
**The first line of error output in that screenshot is more indicative - there was actually a problem with mpicc and mpicxx, because it ends up without the C and CXX found variables set**

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #1336

### CODE REVIEW

**Comment by lifflander** [comment]
Is this ready to go?

**Comment by cz4rs** [comment]
> Is this ready to go?

Not yet, I've just made it report success for a moment to see the logs in detail. In the end, I'll try to make it work with building and caching (as discussed on Slack).

**Comment by lifflander** [comment]
Is there a bug in the latest PR I merged?
```
/Users/runner/work/vt/vt/src/vt/context/context.cc:125:29: error: no member named 'Trace' in namespace 'vt::ctx'; did you mean simply 'Trace'?
    auto t = getTask()->get<ctx::Trace>();
                            ^~~~~~~~~~
                            Trace
/Users/runner/work/vt/vt/src/vt/handler/handler.h:90:3: note: 'Trace' declared here
  Trace      = eHandlerBits::Functor  + functor_num_bits,
  ^
/Users/runner/work/vt/vt/src/vt/context/context.cc:125:25: error: no matching member function for call to 'get'
    auto t = getTask()->get<ctx::Trace>();
             ~~~~~~~~~~~^~~~~~~~~~~~~~~
/Users/runner/work/vt/vt/src/vt/runnable/runnable.impl.h:55:17: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'T'
T* RunnableNew::get() {
                ^
```

**Comment by cz4rs** [comment]
> Is there a bug in the latest PR I merged?
> 
> ```
> /Users/runner/work/vt/vt/src/vt/context/context.cc:125:29: error: no member named 'Trace' in namespace 'vt::ctx'; did you mean simply 'Trace'?
>     auto t = getTask()->get<ctx::Trace>();
>                             ^~~~~~~~~~
>                             Trace
> /Users/runner/work/vt/vt/src/vt/handler/handler.h:90:3: note: 'Trace' declared here
>   Trace      = eHandlerBits::Functor  + functor_num_bits,
>   ^
> /Users/runner/work/vt/vt/src/vt/context/context.cc:125:25: error: no matching member function for call to 'get'
>     auto t = getTask()->get<ctx::Trace>();
>              ~~~~~~~~~~~^~~~~~~~~~~~~~~
> /Users/runner/work/vt/vt/src/vt/runnable/runnable.impl.h:55:17: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'T'
> T* RunnableNew::get() {
>                 ^
> ```

bc07007 fixes this (we cannot add `trace.h` header unconditionally because it would mess up `trace_only` by pulling in `checkpoint`).

**Review by jstrzebonski — APPROVED** [review]
Looks good.

**Review by JacobDomagala — APPROVED** [review]
🚀

**Comment by cz4rs** [comment]
gcc-7 failure is due to no space left on device:
image

**Review by lifflander — APPROVED** [review]
Looks good

**Pull request merged**
