### PR TITLE
1073 Include checkpoint in generated doxygen

### LINKED ISSUE #1073: Update auto-build docs workflow to include checkpoint and detector
**What Needs to be Done?**

When running the workflow to generate the doxygen website, add checkpoint to the generation.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #1073

### CODE REVIEW

**Review by jstrzebonski — APPROVED** [review]

**Review by cz4rs — CHANGES_REQUESTED** [review]
looks good to me, but CI complains about trailing whitespace (docs/Doxyfile.in:818-819)

**Review by JacobDomagala — APPROVED** [review]

**Comment by lifflander** [comment]
> looks good to me, but CI complains about trailing whitespace (docs/Doxyfile.in:818-819)

Somehow, ^M got inserted but I don't know why.

**Review by cz4rs — APPROVED** [review]

**Comment by cz4rs** [comment]
> Somehow, ^M got inserted but I don't know why.

now it seems that the whole `Doxyfile.in` file was updated, some editor / system settings changed?

**Comment by lifflander** [comment]
> > Somehow, ^M got inserted but I don't know why.
> 
> now it seems that the whole `Doxyfile.in` file was updated, some editor / system settings changed?

Yes, I had to change the encoding from DOS to regular unix. The whole file had the wrong line encodings in it.

**Pull request merged**
