### PR TITLE
931 fix Mac CI target

### LINKED ISSUE #931: Fix the Mac CI target
**What Needs to be Done?**

Every since a few days ago the Mac CI platform has been failing during the run test stage of job. It seems possibly related to mpich gethostname, but the question is what changed for this to consistently fail. The Mac platform is nailed down to Mac OS X Catalina (10.15) with a set of brew packages in the Brewfile `vt/ci/Brewfile`.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #931﻿

### CODE REVIEW

**Comment by PhilMiller** [comment]
Not that I disagree in the slightest, but you may want to rebase to amend that commit message

**Comment by lifflander** [comment]
> Not that I disagree in the slightest, but you may want to rebase to amend that commit message

Yes, I plan to rewrite this once I figure out the solution.

**Comment by lifflander** [comment]
That worked! Finally :)

**Comment by lifflander** [comment]
@PhilMiller I have it working. Can you review/approve?

**Pull request merged**
