### PR TITLE
#872: add encoding member bits in handler field

### LINKED ISSUE #872: Encode member collection handler types in the bit pattern for the handler
**What Needs to be Done?**

Right now, in {send,broadcast}UntypedHandler we pass around a boolean `member` to distinguish the handler type (member vs. function) on the send and receive side after the handler is registered. That bit can easily fit in the 64-bits for `HandlerType`. Encode it, remove it from messages, and from the interface.

### PR DESCRIPTION
**Pull request by jstrzebonski**
* adds encoding member bit in handler field
* cleans up all the places that previously used `member` boolean

Fixes #872

### CODE REVIEW

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/vt/pipe/pipe_manager_tl.impl.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6353892&bid=20630032)

**Comment by PhilMiller** [comment]
The code broadly looks fine, but the universal test failures indicate that something got missed in the changes

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/vt/pipe/pipe_manager_tl.impl.h  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6353892&bid=20630032)

**Comment by jstrzebonski** [comment]
The branch was named wrongly. I've created another PR for this -> #1118

**Pull request closed without merging**
