### PR TITLE
#2084: Create release `1.3.0` (`git merge` approach)

### LINKED ISSUE #2084: Create release `1.3.0`
**What Needs to be Done?**
- [x] Create PR to sync `main` with `develop`
- [x] Prepare release notes
- [x] Make sure to update `VERSION` file

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #2084 

Try another way of handling the history:
```
git checkout main
git checkout -b 2084-release-1-3-0-merge
git merge -X theirs origin/develop
git status
(...)
git rm ci/azure/azure-clang-5.0-ubuntu-mpich.yml 
git rm ci/azure/azure-gcc-7-ubuntu-mpich.yml 
git add src/vt/messaging/async_op_hip.h 
git merge --continue 
git cherry-pick 7ac436c9a
```

The remaining differences are handled with https://github.com/DARMA-tasking/vt/pull/2128/commits/348fb8eff3f1df0e8e25241a7caecf12b00c89cf.

### CODE REVIEW

**Comment by cz4rs** [comment]
With this approach `git log main..develop` will show history correctly as Phil [has requested](https://github.com/DARMA-tasking/vt/pull/2114#issuecomment-1490529525).

**Comment by cz4rs** [comment]
> @cz4rs Why does this PR target `develop` instead of `main`?

My bad :facepalm:

**Comment by cz4rs** [comment]
Source code is in sync now:
```diff
git diff develop..2084-release-1-3-0-merge

diff --git a/VERSION b/VERSION
index 23aa83906..f0bb29e76 100644
--- a/VERSION
+++ b/VERSION
@@ -1 +1 @@
-1.2.2
+1.3.0
```

**Comment by nlslatt** [comment]
@cz4rs @PhilMiller @lifflander Is this the one we want to merge, without the signed commit? I don't see an option to override the requirement here. Do we just turn off the requirement in the branch settings, merge, and then turn it back on?

**Comment by cz4rs** [comment]
> @cz4rs @PhilMiller @lifflander Is this the one we want to merge, without the signed commit? I don't see an option to override the requirement here. Do we just turn off the requirement in the branch settings, merge, and then turn it back on?

Sounds reasonable to me.

**Pull request merged**
