### PR TITLE
#1408: Add pmpi/generated to list of potential source directories

### LINKED ISSUE #1408: PMPI Wrappers for MPI guards fail to build in embedded setting
**Describe the bug**

A CLANG-DEBUG build with vt as an embedded TPL fails to link like this:

```
TPL/vt/src/libvt-debug.a(runtime.cc.o):runtime.cc:function vt::pmpi::PMPIComponent::startup(): error: undefined reference to 'vt::pmpi::PMPIComponent::registerEventHandlers()'
```

Disabling `vt_mpi_guards` in the CMake configuration averts the error.

The subdirectory listing in `src/CMakeLists.txt` is missing `pmpi/generated`

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #1408

### CODE REVIEW

**Comment by PhilMiller** [comment]
Tested in both the disabled and enabled cases, and the code configures, compiles, and links both ways.

**Comment by JacobDomagala** [comment]
Isn't the the issue that we include `include(../cmake/define_build_types.cmake)` (which defines `vt_mpi_guards` build option) after we try to generate `PMPI` wrappers? I could be wrong, but https://github.com/DARMA-tasking/vt/pull/1360 looks like the actual fix for this.

**Comment by PhilMiller** [comment]
Agreed, 1360 may be the proper fix for this.

**Comment by PhilMiller** [comment]
Obviated by #1360, confirmed in EMPIRE that compilation succeeds immediately after the initial CMake configuration, with no second pass to cover for it.

**Pull request closed without merging**
