### PR TITLE
#1320: put a direct link to Azure builds in PR comment

### LINKED ISSUE #1320: Put a direct link to Azure builds in PR comment
Quoting @JacobDomagala comment in #1319 :

Would it be possible to include a direct link to the build as well? That'd be great to have, instead of having to click through 4 pages to see the logs. 

Assuming the Azure provides the variables for BUILD_ID, JOB_ID and TASK_ID it should be fairly easy to generate the URL as follows:
https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId={BUILD_ID}&view=logs&j={JOB_ID}&t={TASK_ID}

And then the comment would include that link like so:
> **PR tests (gcc-7, ubuntu, mpich, trace runtime, LB)**
> Build for 14d832ded591db8bf31e6b77ea575c111b974d5e
> 
> ```
> Compilation - successful
> 
> The following tests FAILED:
>    79 - vt:*/TestNodeStatsDumper.test_node_stats_dumping_with_interval/*_proc_2 (Failed)
> ```
> 
> For details go to -> [Build Logs](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=9427&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2)

***

Let's investigate if it's possible to easily generate such links.

### PR DESCRIPTION
**Pull request by jstrzebonski**
Fixes #1320

### CODE REVIEW

**Comment by jstrzebonski** [comment]
I think it works quite nice:
image

**Review by lifflander — APPROVED** [review]
Yes, this is quite convenient!

**Review by JacobDomagala — APPROVED** [review]
🚀

**Review by cz4rs — APPROVED** [review]
Looks good to me :100:

**Pull request merged**
