### PR TITLE
#1856: This adds a script to run the build and test using cmake

### LINKED ISSUE #1856: Rename cdash config file
**What Needs to be Done?**

Rename `CTestConfiguration.ini` to `CTestConfig.cmake` for the benefit of CDash reporting.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by prwolfe**
I have not tested this as the compiler is failing
on a different .o file each run. I will set up the
changes needed in the vt-ci as well, but I don't
expect I will get it tested before leaving for vacation.
Note that use of a ctest script might  have been
a better pattern, but both are claimed to work in
the documentation.

Fixes #1856

### CODE REVIEW

**Comment by nlslatt** [comment]
Based on what Paul said in the PR description, it sounds like the build parallelism limit potentially isn't being respected. I will start playing with this and see if I can get it working.

**Comment by nlslatt** [comment]
I'm not seeing any XML files being generated, so it would appear that there's nothing to submit to the dashboard. I'm not sure that `-M Continuous` and `--build-and-test` are meant to be combined as they are discussed only separately in the documentation I'm looking at. I think we might need to make a dashboard script (https://cmake.org/cmake/help/latest/manual/ctest.1.html#ctest-script), which could be annoying because it will have to specify all the `-D` options we want passed to cmake when configuring.

**Comment by nlslatt** [comment]
@prwolfe Do you think this is ready to test in production?

**Comment by nlslatt** [comment]
> @nlslatt - I figured out that the commit message pattern you are using is why a lot of the checks are failing. I saw you added "#1856: " to each message, but the way I have git configured I am unable to insert a leading '#'. How are you going about that?

@prwolfe Add the following two lines to your `.gitconfig` file:
```
[core]
        commentChar = ";"
```

**Comment by prwolfe** [comment]
> > @nlslatt - I figured out that the commit message pattern you are using is why a lot of the checks are failing. I saw you added "#1856: " to each message, but the way I have git configured I am unable to insert a leading '#'. How are you going about that?
> 
> @prwolfe Add the following two lines to your `.gitconfig` file:
> 
> ```
> [core]
>         commentChar = ";"
> ```

I found that. I think this is ready to go in and we will need to merge the branch in vt-ci just before it to get everything to report.

**Comment by nlslatt** [comment]
@prwolfe It looks like the main thing you're missing right now is signing your commits: https://docs.github.com/en/authentication/managing-commit-signature-verification

**Comment by nlslatt** [comment]
@prwolfe I fixed the signing this time so the PR checks have time to go through.

**Comment by prwolfe** [comment]
Thank you! I will set mine up ASAP.

Paul

From: Nicole Slattengren ***@***.***>
Reply-To: DARMA-tasking/vt ***@***.***>
Date: Monday, July 11, 2022 at 11:40 AM
To: DARMA-tasking/vt ***@***.***>
Cc: "Wolfenbarger, Paul R" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [DARMA-tasking/vt] #1856: This adds a script to run the build and test using cmake (PR #1858)


@prwolfe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprwolfe&data=05%7C01%7Cprwolfe%40sandia.gov%7C6f3e24d24c8d4726f2ff08da63647692%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637931580384146652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FeqQYaslAuSo4MmypZ2TLeEE5ia%2FUKR9VxkchBbmseY%3D&reserved=0> I fixed the signing this time so the PR checks have time to go through.

**Pull request merged**
