### PR TITLE
1679:  Create `1.1.1 beta v7` release candidate

### LINKED ISSUE #1679: Create `1.1.1 beta v7` release candidate
**What Needs to be Done?**

- [x] Check why `main` appears to be ahead of `develop`
- [x] Create PR (`develop` -> `main`); include #1673 but not #1657 (test the latter on more machines before putting it on main)
- [x] Prepare release notes
- [x] Update wiki

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #1679 

Issues included:
- #1445 
- #1550
- #1636 
- #1667 
- #1673
- #1677  
- #1680
- #1685 
- #1692 

Skipped:
- #1657

### CODE REVIEW

**Comment by cz4rs** [comment]
Alpine build fails because it uses newer (promoted from `develop`) version of docker image. I believe this is good to go.

**Comment by cz4rs** [comment]
Should we wait for #1683 (git header information)?

**Comment by nlslatt** [comment]
> Should we wait for #1683 (git header information)?

@cz4rs That one should be ready to add now.

**Review by nlslatt — APPROVED** [review]
Looks good.

**Comment by nlslatt** [comment]
Let's add one more PR for fixing the git revision issue that is showing up in the `pushdockerimage` for `develop` once it has been completed.

**Review by lifflander — APPROVED** [review]
Looks good to me!

**Review by nlslatt — APPROVED** [review]

**Pull request merged**
