### PR TITLE
1920 update mac build

### LINKED ISSUE #1920: Upgrade macOS CI image
**What Needs to be Done?**
The macOS 10.15 Actions runner image is being deprecated, see https://github.com/actions/runner-images/issues/5583 for details.
Upgrade it to a more recent, supported version.

---
Note: there's another issue with the macOS build reported by @PhilMiller:
> The macOS CI build always seems to download an empty cache, and so take longer to re-run than any of the Linux targets. Is there a missing upload, broken key, or something?

Investigate this when upgrading the build or create a separate issue if needed.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #1920

### CODE REVIEW

**Comment by thearusable** [comment]
Looks like macos jobs is working fine now: https://github.com/DARMA-tasking/vt/actions/runs/3650031194/jobs/6165492825

**Review by cz4rs — APPROVED** [review]
Looks good to me!
I think that using `latest` instead of a fixed version is fine here, new version of `macos` doesn't show up too often ;)

**Review by nlslatt — DISMISSED** [review]
The `NOMERGE` commits need to be rebased out.

**Comment by nlslatt** [comment]
> The `NOMERGE` commits need to be rebased out.

In the interests of getting this merged, I'm going to squash the commits to eliminate the `NOMERGE` problem and all the extraneous debugging commits.

**Review by nlslatt — APPROVED** [review]

**Comment by thearusable** [comment]
> > The `NOMERGE` commits need to be rebased out.
> 
> In the interests of getting this merged, I'm going to squash the commits to eliminate the `NOMERGE` problem and all the extraneous debugging commits.

@nlslatt Thanks! Sorry I somehow missed you previous comment.

**Review by JacobDomagala — APPROVED** [review]

**Comment by PhilMiller** [comment]
I'm not a huge fan of unspecified 'latest' versions, but the rest of the team has clearly spoken. Merging.

**Pull request merged**
