### PR TITLE
#2340: Fix missing NumPy package

### LINKED ISSUE #2340: Python script fails to install numpy in docker container for gcc-9.
Discovered in #2174 

https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=61530&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2

### PR DESCRIPTION
**Pull request by thearusable**
Fixes #2340

### CODE REVIEW

**Comment by thearusable** [comment]
The issue was caused by a bug in DeepDiff v7. The NumPy dependency wasn't properly set up, so it wasn't installed, but it was required by a module from DeepDiff. After the change in the PR, the Docker image will be rebuilt, and the newest version of DeepDiff will be downloaded, which contains a bugfix for that issue.

From the logs on develop, pushing a Docker image to Docker Hub seems to work correctly.

**Review by cwschilly — APPROVED** [review]
This fixed the problem on #2294

**Review by cz4rs — APPROVED** [review]

**Comment by thearusable** [comment]
This PR is not technically necessary to be merged. The new image was pushed from a modified CI run, and this change was needed as a trigger to rebuild the image. The PR only removes a duplicated entry for `python3` on the packages list for `apt`.

**Review by nlslatt — APPROVED** [review]

**Comment by nlslatt** [comment]
This PR contained an incidental fix that was not strictly necessary for fixing the missing numpy package.

**Pull request merged**
