### PR TITLE
#1088: Always use -std=c++14 for GCC and not earlier experimental -std=c++1y

### LINKED ISSUE #1088: nvcc complains about use of -std=c++1y vs -std=c++14
**Describe the bug**

Compilation with Nvidia's compiler produces these messages for every file compiled, for versions 10.1 and 11.0:
```
nvcc_wrapper does not accept standard flags -std=c++1y since partial standard flags and standards after C++14 are not supported. nvcc_wrapper will use -std=c++14 instead. It is undefined behavior to use this flag. This should only be occurring during CMake configuration.
nvcc_wrapper - *warning* you have set multiple standard flags (-std=c++1* or --std=c++1*), only the last is used because nvcc can only accept a single std setting
```

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #1088

### CODE REVIEW

**Review by lifflander — APPROVED** [review]

**Comment by PhilMiller** [comment]
It cuts down half the errors. Now just getting
```
nvcc_wrapper - *warning* you have set multiple standard flags (-std=c++1* or --std=c++1*), only the last is used because nvcc can only accept a single std setting
```

**Comment by PhilMiller** [comment]
Detector and Checkpoint both produce this complaint, which may be the culprit if the flags are inherited and incorporated:
```
nvcc_wrapper has been given GNU extension standard flag -std=gnu++14 - reverting flag to -std=c++14
```

**Comment by PhilMiller** [comment]
I'm inclined to get this bit merged, and leave the other warning for a new issue, for someone else to dig into.

**Comment by PhilMiller** [comment]
Opened #1090 for the latter

**Pull request merged**
