### PR TITLE
1808: Add build for the latest icpc version

### LINKED ISSUE #1808: Add build for the latest `icpc` version
**What Needs to be Done?**
Add Azure build for icpc 2021.6.0 and try to fix any appearing warnings.

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #1808

### CODE REVIEW

**Comment by cz4rs** [comment]
@jstrzebonski Can you please add the Azure job for `icpc` build?

**Comment by jstrzebonski** [comment]
> @jstrzebonski Can you please add the Azure job for `icpc` build?

@cz4rs Done!
obraz

**Review by PhilMiller — COMMENTED** [review]
Could you name the build icpx with the compiler version number, instead of icpc? Two different generations of Intel compiler. Icpx is newer, and based on clang

**Comment by cz4rs** [comment]
> Could you name the build icpx with the compiler version number, instead of icpc? Two different generations of Intel compiler. Icpx is newer, and based on clang

`icpx` build is still present, `icpc` is the newly added one:
image

This way we have tests for both clang-based and "classic" version:
```
PR tests (intel icpc, ubuntu, mpich)
(...)
-- The C compiler identification is Intel 2021.6.0.20220226
-- The CXX compiler identification is Intel 2021.6.0.20220226
```
```
PR tests (intel icpx, ubuntu, mpich)
(...)
-- The C compiler identification is IntelLLVM 2022.1.0
-- The CXX compiler identification is IntelLLVM 2022.1.0
```

**Review by PhilMiller — APPROVED** [review]

**Comment by PhilMiller** [comment]
I see now. Looks good

**Pull request merged**
