### PR TITLE
619 tr begin may be used uninitialized

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Comment by PhilMiller** [comment]
Obviously don't even try to review or merge this. Something is weird in what this is based on, since it should represent just a single new commit.

**Comment by pnstickne** [comment]
@lifflander Trivially-simple PR, ideal to merge into beta-5.

Per conversation earlier I may also plan put a PR based on develop to re-integrate sooner.

**Comment by lifflander** [comment]
Why aren't checks running for these PRs into 1.0.0-*?

**Comment by PhilMiller** [comment]
> Why aren't checks running for these PRs into 1.0.0-*?

`.travis.yml` isn't present on the branch, would be my guess.

**Comment by lifflander** [comment]
Merged. closing

**Pull request closed without merging**
