### PR TITLE
#1056: Run LB starting after phase 1 by default

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes: #1056

### CODE REVIEW

**Review by lifflander — APPROVED** [review]
Looks good to me!

**Comment by lifflander** [comment]
Rebase and the CI failure will go away. I've fixed them on develop.

**Comment by PhilMiller** [comment]
I just had to rebase and await CI checks again because my rebase on an SNL server wasn't signed. We should probably add that as a commit check, so it's obvious that merging will be impossible before waiting on all the other tests to pass.

**Comment by PhilMiller** [comment]
Opened #1061 accordingly

**Comment by PhilMiller** [comment]
At least ccache is working reasonably for many of the checks

**Pull request merged**
