### PR TITLE
1423 remove maximimum ref-count check

### LINKED ISSUE #1423: Message ref-count limit triggers in simple cases
**Describe the bug**
When running `lb_iter`, I'm getting this assertion when I set the number of elements high enough:

```
vt: [0]              Reason: Bad ref-count on message ref-increment. Message ref-count must never be negative and cannnot exceed limit (100).
vt: [0]    Assertion failed: (envp->ref >= 0 and envp->ref < 100)
vt: [0]                Node: 0
vt: [0]           Num Nodes: 2
vt: [0]                File: /Users/nlslatt/work/vt/vt-tmp/src/vt/messaging/envelope/envelope_ref.impl.h
vt: [0]                Line: 68
vt: [0]            Function: envelopeRef
vt: [0]                Code: 1
```

I've seen this with GossipLB and RandomLB.  I haven't tried other LBs.

**To Reproduce**

`mpirun -np 2 ./examples/collection/lb_iter 200 1 5 --vt_lb --vt_lb_interval=1 --vt_lb_name=RandomLB`

or

`mpirun -np 2 ./examples/collection/lb_iter 200 1 5 --vt_lb --vt_lb_interval=1 --vt_lb_name=GossipLB`

Reducing the number of elements from 200 to 100 does not trigger the assertion.  This is on my Mac.

### PR DESCRIPTION
**Pull request by stmcgovern**
Fixes #1423 by simply removing the upper bound check in the assertion.
Alternative to PR #1432

### CODE REVIEW

**Comment by stmcgovern** [comment]
Line 65 comment should be amended to "Message ref-count must never be negative."

**Review by lifflander — APPROVED** [review]
Looks good to me! Just need to get the warnings worked out.

**Comment by PhilMiller** [comment]
Code looks fine to me.

**Comment by stmcgovern** [comment]
> Looks good to me! Just need to get the warnings worked out.

- They seem to be related to type conversions (mostly in pipe manager) only when using cuda.
- Here in /vt/src/vt/configs/types/types_sentinels.h(78): warning: integer conversion resulted in a change of sign
`static constexpr RefType const not_shared_message                  = -1000;`
Since that RefType is now uint16  initializing to -1000 no longer makes sense, right?

**Pull request merged**
