### PR TITLE
1782: fix dangling pointer warning

### LINKED ISSUE #1782: dangling pointer warning (`gcc-12`)
**Describe the bug**
[gcc-12 build](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=32691&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2) shows a new warning:
```
/vt/src/vt/group/region/group_list.cc: In member function 'virtual void vt::group::region::List::splitN(int, vt::group::region::Region::ApplyFnType) const':
/vt/src/vt/group/region/group_list.cc:164:31: warning: dangling pointer to an unnamed temporary may be used [-Wdangling-pointer=]
  164 |     for (int i = cur_idx; i < cur_max; i++) {
      |                               ^~~~~~~
/vt/src/vt/group/region/group_list.cc:162:22: note: unnamed temporary defined here
  162 |       size : std::min(size, cur_idx + child_size);
      |              ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Overall the code involved seems to be using references to `int` overzealously:
https://github.com/DARMA-tasking/vt/blob/be0a753bd3adbec6b02563d86f83597e35a8e7e9/src/vt/group/region/group_list.cc#L155-L162
**Expected behavior**
Remove the unnecessary `&`.

### PR DESCRIPTION
**Pull request by cz4rs**
fixes #1782

### CODE REVIEW

**Comment by jstrzebonski** [comment]
It seems that it might be a good idea to get back to issue #874

**Review by jstrzebonski — APPROVED** [review]
Looks good to me.

**Review by PhilMiller — APPROVED** [review]

**Comment by cz4rs** [comment]
Rebased on top of `develop`.

**Review by lifflander — APPROVED** [review]
Looks good

**Review by JacobDomagala — APPROVED** [review]

**Pull request merged**
