### PR TITLE
#1807: use gtest 1.11.0

### LINKED ISSUE #1807: consider updating GTest version
**What Needs to be Done?**
- [ ] Update GTest to a more recent version
- [ ] Verify that our tests work correctly with the new GTest

### PR DESCRIPTION
**Pull request by stmcgovern**
Fixes #1807. Updates fetch script and bundled gtest to version 1.11.0.

### CODE REVIEW

**Comment by stmcgovern** [comment]
> > **PR tests (intel icpx, ubuntu, mpich)**
> > Build for [98abadc](https://github.com/DARMA-tasking/vt/commit/98abadc96d25be121a7554909da11506442b119a)
> > ```
> > In file included from /vt/tests/extern/googletest/googletest/src/gtest-all.cc:41:
> > /vt/tests/extern/googletest/googletest/src/gtest.cc:1583:8: warning: comparison with NaN always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
> >   if (!(std::isnan)(val1) && !(std::isnan)(val2) && abs_error > 0 &&
> >        ^~~~~~~~~~~~~~~~~~
> > /vt/tests/extern/googletest/googletest/src/gtest.cc:1583:31: warning: comparison with NaN always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
> >   if (!(std::isnan)(val1) && !(std::isnan)(val2) && abs_error > 0 &&
> >                               ^~~~~~~~~~~~~~~~~~
> > 2 warnings generated.
> > 
> > Testing - passed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Build log](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=35342&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2)
> 
> It seems that gtest is not getting our flags `-fhonor-infinities -fhonor-nans` passed through to it. Did we have a modified gtest CMake file to support that?

The warnings are still there using the existing CMake file (with version updated to 1.11.0). Note: The code lines that produce these warnings are new to gtest 1.11.0.

**Review by cz4rs — APPROVED** [review]
Looks good to me!

**Comment by stmcgovern** [comment]
> One question: `LICENSE` file gets removed in this PR. Is the license / copyright statement still present somewhere?
They remove the LICENSE out of the googletest subfolder between versions. There is still a license at the top level googletest directory.
Compare: 
https://github.com/google/googletest/tree/release-1.11.0/googletest
https://github.com/google/googletest/tree/release-1.10.0/googletest

**Comment by nlslatt** [comment]
> 

I think we should pull the `LICENSE` file from the top-level directory, then. Does anyone think we need ot pull additional files in from there?

**Review by cz4rs — DISMISSED** [review]
> I think we should pull the `LICENSE` file from the top-level directory, then. Does anyone think we need ot pull additional files in from there?

~`LICENSE` file should be enough. Looks good apart from that.~

**Review by cz4rs — APPROVED** [review]
Looks good to me.

`vt/tests/extern/googletest/LICENSE` is still present, only the copy in `vt/tests/extern/googletest/googletest/LICENSE` is removed (these files are identical).

**Review by nlslatt — APPROVED** [review]
Looks good

**Pull request merged**
