### PR TITLE
#558: Support migrating responsibility for object control flow

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Comment by lifflander** [comment]
I think it would be preferable for this to be named after the VT issue #558 so we can track it on the release

**Comment by PhilMiller** [comment]
Does your tracking script look only at non-merge commits? If it considers issue numbers in all commits, then having it in the merge should suffice.

**Comment by lifflander** [comment]
@PhilMiller It looks at both merge and non-merge commits. The problem is that it can't correlate a PR # to the Issue # unless the PR title is prefixed with the issue #. Github does not automatically connect the two in the json.

**Comment by PhilMiller** [comment]
Is there a reason not to go ahead with merging this?

**Comment by lifflander** [comment]
Closing in favor of #562

**Pull request closed without merging**
