### PR TITLE
1361: Merge  beta.10.4.1 proposed update into 1.0

### PR DESCRIPTION
**Pull request by lifflander**

### CODE REVIEW

**Comment by lifflander** [comment]
I think I want to actually merge this into it's own branch first.

**Comment by lifflander** [comment]
@nlslatt I don't want to merge this, but this clearly shows the diff for this version. I want to call this 1.0.1

**Comment by cz4rs** [comment]
Looking at the issues tagged [`1.0.0-beta.10.4.1`](https://github.com/DARMA-tasking/vt/issues?q=is%3Aissue+label%3A1.0.0-beta.10.4.1+):
- https://github.com/DARMA-tasking/vt/issues/1338 is missing
- #1296 and #1279 can probably be closed manually
- some of the fixes have not landed on `develop` - should we create an issue to track this?

Also, if we are going for the `1.0.1` tag, should any of [these](https://github.com/DARMA-tasking/vt/issues?q=is%3Aissue+label%3A1.0.1+) be included?

**Review by cz4rs — APPROVED** [review]
Looks good to me

**Pull request merged**
