### PR TITLE
1215: Use prebuilt docker image for vt:develop image creation

### LINKED ISSUE #1215: Make develop CI target "Docker Image CI" use base image
**What Needs to be Done?**

Right now, the `Docker Image CI` GitHub workflow that pushes the latest VT image install to Docker Hub starts from the base ubuntu image. Make that start from a pre-build image (like `lifflander1/vt:amd64-ubuntu-18.04-gcc-7-cpp`) and includes all the dependencies.

### PR DESCRIPTION
**Pull request by JacobDomagala**
Fixes #1215

### CODE REVIEW

**Review by cz4rs — APPROVED** [review]
looks good overall

are you going to test the workflow while still on the branch? (adding branch name here should be enough)
https://github.com/DARMA-tasking/vt/blob/ee1636d8906174ca72fe395db17071ebd143ce96/.github/workflows/pushdockerimage.yml#L6-L9

**Review by lifflander — APPROVED** [review]
Looks good

**Comment by JacobDomagala** [comment]
> looks good overall
> 
> are you going to test the workflow while still on the branch? (adding branch name here should be enough)
> https://github.com/DARMA-tasking/vt/blob/ee1636d8906174ca72fe395db17071ebd143ce96/.github/workflows/pushdockerimage.yml#L6-L9

@cz4rs  I've added temporary test workflow https://github.com/DARMA-tasking/vt/pull/1264/checks?check_run_id=2015463927 to test the build. No need to push the image to remote i think. 

Will revert the commit with the new workflow before merging this PR

**Comment by JacobDomagala** [comment]
Ok docker images built fine https://github.com/DARMA-tasking/vt/actions/workflows/test_build.yml

Reverted the commit and will merge this PR

**Pull request merged**
