### PR TITLE
#586: cleanup minor ordering/formatting in args.cc

### PR DESCRIPTION
**Pull request by pnstickne**
- Moved 'colorize_output' to related options

- Added/removed newlines for consistency

- 'auto' -> 'int' for clarity 'cause'

### CODE REVIEW

**Comment by pnstickne** [comment]
@lifflander Free close-the-story merge.

**Comment by PhilMiller** [comment]
This looks fine, but why is it important on the release branch?

**Comment by lifflander** [comment]
@pnstickne Why is this not targeting develop?

**Comment by pnstickne** [comment]
Not essential. Changes have already been duplicated elsewhere.

**Pull request closed without merging**
