### PR TITLE
554 demangler chk 1.0

### PR DESCRIPTION
**Pull request by pnstickne**
As on origin/develop. Cherry-pick'ed up.
- examples/reduce runs without errors

### CODE REVIEW

**Comment by pnstickne** [comment]
Where did the build checks go..?

**Comment by lifflander** [comment]
Since you're merged into the proposed update, it's not running them.

**Comment by pnstickne** [comment]
@lifflander Changes are the same, this was cherry-picked from the branch originally based on develop.

**Comment by lifflander** [comment]
Merged, closing

**Pull request closed without merging**
