### PR TITLE
#2312: Update CI jobs to resolve all warnings.

### LINKED ISSUE #2312: Update CI to use Docker Compose V2 on Azure
Warning to be fixed:
The task is utilizing Docker Compose V1, but there are plans to transition to Docker Compose V2. It's necessary to investigate how to adapt your project to Docker Compose V2. For guidance on this migration, you can refer to the official Docker Compose documentation at the provided link: https://docs.docker.com/compose/migrate/

### PR DESCRIPTION
**Pull request by thearusable**
Closes #2312

### CODE REVIEW

**Review by cz4rs — APPROVED** [review]
Looks good to me :slightly_smiling_face:

**Review by lifflander — APPROVED** [review]
Looks great!

**Comment by lifflander** [comment]
Should all the pipelines be succeeding after this PR?

**Comment by lifflander** [comment]
Ah, I think a change a magistrate might have broken this.

**Comment by cz4rs** [comment]
```
  Target "vt" links to:

    vt::lib::checkpoint

  but the target was not found.
```
Do we still want to support this `vt::lib::checkpoint` notation or just `vt::checkpoint`?

**Comment by JacobDomagala** [comment]
> Ah, I think a change a magistrate might have broken this.

I'll try to fix that -> https://github.com/DARMA-tasking/magistrate/issues/356

**Review by JacobDomagala — APPROVED** [review]

**Review by cz4rs — APPROVED** [review]

**Pull request merged**
