### PR TITLE
#1763 build only ready prs

### LINKED ISSUE #1763: Only run CI automatically when PR is not in draft mode
**What Needs to be Done?**

- Instead of always running on a push, only run if not in draft mode.
- Make sure we are cancelling workflows when new code is pushed
- Maybe allow an override comment for PRs in draft mode

### PR DESCRIPTION
**Pull request by jstrzebonski**
Fixes #1763 

---

TODO:

- [x] Run build only if PR is ready for review
- [x] Cancel ongoing builds when new code is pushed
- [x] Cancel ongoing builds when new code is pushed on macOS pipeline
- [x] Turn off building drafts for macOS pipeline
- [x] Allow running builds even if PR is in draft mode - maybe by a special comment or label? - Cannot be done in any satisfactory way.
- [x] Add a label that, if absent, blocks PR from being merged - moved to #1861

### CODE REVIEW

**Comment by nlslatt** [comment]
@jstrzebonski Is this actually ready for review or are you still testing the label?

**Review by nlslatt — DISMISSED** [review]
Looks good to me.

**Comment by jstrzebonski** [comment]
> @jstrzebonski Is this actually ready for review or are you still testing the label?

@nlslatt Almost done, but I'm still testing one possible solution to the last TODO item.

**Comment by nlslatt** [comment]
> image
> 
> At the moment merging is blocked by a lack of approvals. To fully check `Allow merging` action I need at least one.

I'm keeping an eye on it. There's still a PR test left to complete before we can find out anyway.

**Comment by jstrzebonski** [comment]
> > image
> > At the moment merging is blocked by a lack of approvals. To fully check `Allow merging` action I need at least one.
> 
> I'm keeping an eye on it. There's still a PR test left to complete before we can find out anyway.

Thanks!

**Review by nlslatt — DISMISSED** [review]
Testing whether it allows merging with approval with the allow-merge check skipped due to not having the label

**Review by nlslatt — CHANGES_REQUESTED** [review]
It looks like a skipped required check does not block merging. We'll probably need to make it fail rather than skip.

**Comment by jstrzebonski** [comment]
> It looks like a skipped required check does not block merging. We'll probably need to make it fail rather than skip.

@nlslatt Fixed. Should be fine now.

**Review by JacobDomagala — APPROVED** [review]

**Comment by jstrzebonski** [comment]
Marking as a draft until I move last commit to a new branch.

**Comment by jstrzebonski** [comment]
> Marking as a draft until I move last commit to a new branch.

Done.

**Review by nlslatt — APPROVED** [review]

**Pull request merged**
