### PR TITLE
#1701 Adding New Jacobi3D Example.

### PR DESCRIPTION
**Pull request by keitat**
This code will be used to study resilience capability of DARMA-VT and Kokkos.

### CODE REVIEW

**Comment by keitat** [comment]
The error indicate the message ref count is greater than 100. When I set the problem smaller, I do not see any errors.  Do you have any suggestions?


            Reason: Bad ref-count on message ref-increment. Message ref-count must never be negative and cannnot exceed limit (100).
vt: [0]    Assertion failed: (envp->ref >= 0 and envp->ref < 100)

**Comment by PhilMiller** [comment]
Ah, you're hitting a guardrail that we implemented to help catch bugs like one Nic ran into. If your task count is such that there are more than 100 assigned to a single process, and you broadcast a message to them, that correctly produces a message with a ref count over this threshold.

**Comment by keitat** [comment]
The PR tests are working fine.  I need approval from the reviewers.

**Comment by PhilMiller** [comment]
For this to eventually be merged, there will need to be a corresponding issue, with suitable references to its number in the commits, branch name, and PR message. This is part of the development process we've documented, to assure traceability of code to requirements.

**Comment by keitat** [comment]
Should I scrap this request and redo PR with the proper branch (1701 ...) from my fork?

**Comment by lifflander** [comment]
> Should I scrap this request and redo PR with the proper branch (1701 ...) from my fork?

Yes, that probably will make things easiest!

**Comment by keitat** [comment]
Let's close the PR.  I will do it again.

**Pull request closed without merging**
