### PR TITLE
#2019: add move constructor/assign to TraceScopedEvent and TraceScopedNote

### LINKED ISSUE #2019: TraceScopedEvent and TraceScopedNote should have deleted copy constructors and defined move constructors/assign
Currently, they only have a deleted copy assignment operator.

### PR DESCRIPTION
**Pull request by nmm0**
Fixes #2019

### CODE REVIEW

**Review by PhilMiller — COMMENTED** [review]
I know calling swap is idiomatic, but I'd be more comfortable if the moved from objects had their event fields assigned the no event value explicitly, moreso in the move assignment case.

**Comment by nmm0** [comment]
> I know calling swap is idiomatic, but I'd be more comfortable if the moved from objects had their event fields assigned the no event value explicitly, moreso in the move assignment case.

For the move constructor it is set explicitly then swapped (from the initializer on event_), but for move assignment it has to use a swap to be correct if not the old value (if it is not `no_trace_event`) will never be released

**Comment by PhilMiller** [comment]
I feel like if that case ever arises, it represents a logic bug, which we should maybe assert against.

What's the actual use case for allowing any sort of move construction or assignment of these types? I figured it was for something like moving into a closure, where there's no existing event to be dealt with.

**Comment by nmm0** [comment]
> I feel like if that case ever arises, it represents a logic bug, which we should maybe assert against.
> 
> What's the actual use case for allowing any sort of move construction or assignment of these types? I figured it was for something like moving into a closure, where there's no existing event to be dealt with.

One I can think of off the top of my head would be an object that needs to extend the lifetime of the TraceScopedEvent/Note until it is passed a new event. When passed a new event (lets say at the end of an iteration or something), it would need to move the new event into its storage, releasing the previous scope.

**Comment by PhilMiller** [comment]
Ok, I'll buy it.

**Review by cz4rs — APPROVED** [review]
Looks good to me.

**Pull request merged**
