### PR TITLE
1507 context td

### LINKED ISSUE #1507: Crash in TD context with thread suspend/resume
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #1507

### CODE REVIEW

**Comment by PhilMiller** [comment]
Tests start breaking at "Reset epoch_stack_size_ in TD::resume() in case underlying stack ..."

**Review by lifflander — APPROVED** [review]
Looks good. Is it possible to add a test for this that exercises the bug?

**Comment by PhilMiller** [comment]
> Looks good. Is it possible to add a test for this that exercises the bug?

Probably.

I don't really want to spend more time on this, since it would mess would my commitments to Kokkos and non-SNL projects

**Review by nlslatt — APPROVED** [review]
This looks good.  My run succeeded this time.

**Comment by nlslatt** [comment]
> > Looks good. Is it possible to add a test for this that exercises the bug?
> 
> Probably.
> 
> I don't really want to spend more time on this, since it would mess would my commitments to Kokkos and non-SNL projects

Is it clear to you exactly what happened to trigger the bug?  Given how far into my run it got before dying, I'm not sure how easily reproducible it is.

**Comment by PhilMiller** [comment]
> > > Looks good. Is it possible to add a test for this that exercises the bug?
> > 
> > 
> > Probably.
> > I don't really want to spend more time on this, since it would mess would my commitments to Kokkos and non-SNL projects
> 
> Is it clear to you exactly what happened to trigger the bug? Given how far into my run it got before dying, I'm not sure how easily reproducible it is.

My suspicion is that it was the first time a thread had been resumed from idle and then ran to completion, thus giving it a slightly different epoch stack. I don't have confirmation for this, though.

I got to the changes made in this PR my inspection and deduction, so I don't have a good empirical point of reference.

**Comment by PhilMiller** [comment]
I just rebased to update, and made a slight syntax tweak, so that the two popping `while` loops would make the same comparison

**Pull request merged**
